kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.alertmanager.configMap.config.name }}
  namespace: {{ .Values.alertmanager.namespace }}
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: {{ .Values.alertmanager.configMap.config.slack.name }}
      group_by: {{ .Values.alertmanager.configMap.config.slack.group_by }}
      group_wait: {{ .Values.alertmanager.configMap.config.slack.wait }}
      repeat_interval: {{ .Values.alertmanager.configMap.config.slack.repeat }}

    receivers:
    - name: {{ .Values.alertmanager.configMap.config.slack.name }}
      slack_configs:
      - api_url: {{ .Values.alertmanager.configMap.config.slack.url_endpoint }}
        channel: {{ .Values.alertmanager.configMap.config.slack.channel }}
        icon_url: https://avatars3.githubusercontent.com/u/3380462