apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo_app.configMap.name }}
  labels: 
  {{- toYaml .Values.demo_app.labels | nindent 4 }}

data:
  DB_NAME: "{{ .Values.postgres.configMap.data.db_name }}"
  DB_HOST: "{{ .Values.postgres.fullname }}.default.svc.cluster.local"
  DB_PORT: "{{ .Values.postgres.service.port }}"