apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.prometheus.namespace }}
  name: {{ .Values.prometheus.configMap.config.name }}
  labels: 
  {{- toYaml .Values.prometheus.labels | nindent 4 }}
data:
  prometheus.rules: |-
    groups:
    - name: Probe-HTTP
      rules:
      - alert: Probe-HTTP
        expr: avg_over_time(http_server_requests_seconds_sum[10m]) > {{ .Values.prometheus.configMap.config.alert_threshold}}
        for: {{ .Values.prometheus.configMap.config.alert_fires }}
        labels:
          severity: critical
        annotations:
          summary: slow HTTP
          description: "HTTP requests on average took more than {{ .Values.prometheus.configMap.config.alert_threshold}}s"
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - prometheus.rules
    alerting:
      alertmanagers:
        - kubernetes_sd_configs:
          - role: service
            selectors:
            - role: "service"
              label: "app={{ .Values.alertmanager.selectorLabels.app }}" 
    scrape_configs:
      - job_name: "prometheus"
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "scrape_api"
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
        - role: pod
          selectors:
          - role: "pod"
            label: "app={{ .Values.demo_app.selectorLabels.app }}"