{{- if .Values.global.db_deploy}}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.postgres.namespace }}
  name: {{ .Values.postgres.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.postgres.pvClaim.storageClass }}
  capacity:
    storage: {{ .Values.postgres.pvClaim.capacity }}
  accessModes: {{- toYaml .Values.postgres.pvClaim.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.postgres.pv.hostPath }}
{{- end}}