apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.demo_app.secret.name }}
  labels: 
  {{- toYaml .Values.demo_app.labels | nindent 4 }}

data:
  DB_USER: "{{ .Values.postgres.secret.data.db_user }}"
  DB_PASS: "{{ .Values.postgres.secret.data.db_master_password }}"