{{- if .Values.global.db_deploy}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.postgres.nammespace }}
  name: {{ .Values.postgres.secret.name }}
  labels: 
  {{- toYaml .Values.postgres.labels | nindent 4 }}

data:
  POSTGRES_USER: "{{ .Values.postgres.secret.data.db_user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.secret.data.db_master_password }}"
{{- end}}