{{- if .Values.global.db_deploy}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.postgres.namespace }}
  name: {{ .Values.postgres.pvClaim.name }}
spec:
  storageClassName: {{ .Values.postgres.pvClaim.storageClass }}
  accessModes: {{- toYaml .Values.postgres.pvClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvClaim.capacity }}
{{- end}}