apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.demo_app.namespace }}
  name: {{ .Values.demo_app.fullname }}
  labels:
    {{- toYaml .Values.demo_app.labels | nindent 4 }}
spec:
  type: {{ .Values.demo_app.service.type }}
  ports:
    - port: {{ .Values.demo_app.service.port }}
      targetPort: {{ .Values.demo_app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.demo_app.selectorLabels | nindent 4 }}
