apiVersion: v2
name: django-app
description: A container-aware Django application chart
type: application
version: 0.1.1
appVersion: "1.0.0"

keywords:
  - django
  - python
  - web

maintainers:
  - name: platform-team
